version: "2.0"

services:
  customer-onboarding:
   build: .
   environment:
    TZ: Europe/Berlin
   ports:
     - 8084:9090
  showcase-worker:
   build: ./external-task-worker/
   environment:
     TZ: Europe/Berlin
   ports:
     - 8085:9090

networks:
  default:
    external:
      name: showroom
